# Numpy (array)

In [11]:
# 1. Numpy is fast as compared to python list because it is build on top of C
# 2. Numpy is also memory efficent
# 3. Numpy does not allow mixed datatpe
# 4. Numpy (operation are easy)
# 5. Numpy has build in function so it is so powerull as compared to python list.

speed.

a = [1,2,3,4,5,6,7] * 100000
= [2,4,6,8]

In [1]:
import time
import numpy as np

a = [1,2,3,4,5,6,7,8,9,10] * 100000
b = np.array(a)
start = time.time()
new_b = b*2
print("\nTime taken for list", time.time() - start)


Time taken for list 0.002008676528930664


In [3]:
import time

a = [1,2,3,4,5,6,7,8,9,10] * 100000

start = time.time()
for i in range(len(a)):
     a[i] = a[i]*2
print("\nTime taken for list", time.time() - start)


Time taken for list 0.13780832290649414


Numpy is build on C 

Numpy is more memory efficent


In [4]:
print(len)
print(range)
print(time)


<built-in function len>
<class 'range'>
<module 'time' (built-in)>


In [5]:
import sys
a = [1,2,3,4,5]
arr = np.array(a)

print("List size", sys.getsizeof(a))

print("Array size:", arr.nbytes)

List size 104
Array size: 40


Direct operationn and vectorization\n

Feature    Python list    Numpy Array

Speed      Slow           Fast (optimized in c)

Data Type  Mixed allowed  Same data type only

Memory 
efficent   less efficient more efficent

Math 
operation  Manual loop    direct(vectorized)

Built-in 
function   Limited        Many powerful tools



In [6]:
import numpy as np # alias ---> np

In [ ]:
np.array([1,2,3,4,5])

array([1, 5])

Dimension

32 --> scaler --> 0 D
[1,2,3,4] --> 1 D

[1,2,3
4,5,6]   --> 2 D



In [21]:
arr = np.array([1,2,3,4,5])
arr.ndim

1

In [20]:
# Dimension and shape of an array

arr = np.array(32)
arr.ndim


0

[]  --> one D
[[]] --> two D
[[[]]] ---> three D

In [9]:
one = np.array([])
one.ndim
#one.shape

1

In [ ]:
two = np.array([[]])
two.ndim


2

In [32]:
three = np.array([[[]]])
three.ndim

3

In [34]:
import pandas as pd

df = pd.read_csv("US500_30D_data")
df.ndim
df.shape

(28220, 8)

Python range

# Numpy functions

Numpy arange

In [2]:
import numpy as np
range = np.arange(1,10,2) # start, stop, step
range

array([1, 3, 5, 7, 9])

Linspace even spaced between two number

In [5]:
arr = np.linspace(0,6,10) # start, stop, no of values
arr

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [12]:
arr = np.logspace(2, 5, 2) #logerithmic scale array --> 10^1 --> 10*3.... 3 points
arr

array([   100., 100000.])

In [49]:
#np.logspace(start, ending --> powers, 3 --> no of points)

In [50]:
# np.zeros --> array full of zeros

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

## np array is used for creating matrix


In [52]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([5,5]) # array of ones
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr = np.ones([3,3])
arr


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [221]:
arr = np.zeros([2,3,5]) # array of ones
arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [60]:
arr = np.full(8,5)
arr

array([5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# Creating array of our choice

arr = np.full([2,4], 7) # [row,colums], default value
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [65]:
arr = np.empty([2,3]) #Uninitilized array --> create an array without setting any valuue
arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.42417901e-306, 6.23058707e-307, 2.22526399e-307]])

In [73]:
arr = np.random.rand(2,3) # Random floats numbers # no square bracket
arr

array([[0.48737505, 0.05575482, 0.8657606 ],
       [0.93313556, 0.67974929, 0.36136878]])

In [ ]:
arr = np.random.randn(2,4) # --> Random floats form standerd normal distriution
arr

array([[-1.23930504,  1.29488061, -0.53673748,  0.94749429],
       [-1.34442583,  0.60043263,  0.09153955,  1.43303222]])

In [92]:
arr = np.random.randint(10,100) # (start, stop , dimension/number)
arr # Radom integer

35

In [ ]:
import random

def guess(x):
     random_number = random.randint(1, x)
     guess = 0

     while guess != random_number:
          guess = int(input("Enter a number :"))
          if guess > random_number:
               print("Too High :")
          elif guess < random_number:
               print("Too Low :")
     print("You guessed it correnct :")

guess(10)


Too Low :
Too Low :
Too Low :
Too Low :
You guessed it correnct :


In [ ]:
# random no matrix
arr = np.random.randint(10, 100, size = (3,3)) # strart, stop, dimensiion
arr

array([[31, 78, 64],
       [61, 30, 51],
       [62, 14, 41]], dtype=int32)

Numpy Data Type and Type Casting

In [111]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [112]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# Typecasting of different datatype because np doesnot suppport different datatpe.

lsit = ["string", 1, 2, 3.4, 4, 5.6]
a = np.array(list)
a

array(<class 'list'>, dtype=object)

In [249]:
# Data Type containing only integers

arr = np.array(["a",1,2,3.1,4,5,6,7])
arr

array(['a', '1', '2', '3.1', '4', '5', '6', '7'], dtype='<U32')

In [120]:
arr.dtype

dtype('<U32')

In [ ]:
# We can convert float to int and int to float

arr = np.array([1,2,3.1,4,5,6,7],dtype = np.int64)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [126]:
arr.dtype

dtype('int64')

In [130]:
# Type casting -> astype()

In [133]:
arr = np.array([1,2,3], dtype = np.float64)
arr.dtype

dtype('float64')

In [138]:
# another method of typecasting

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# Typecasting int ot float
new_arr = arr.astype(np.float64)
new_arr.dtype

dtype('float64')

In [ ]:
# Typecasting float to int
new_arr2 = arr.astype(np.int64)
new_arr2.dtype

dtype('int64')

In [ ]:
# Tupecasting error

arr = np.array(["1","2","hello"])
arr2 = arr.astype(np.int64)
arr2

ValueError: invalid literal for int() with base 10: np.str_('hello')

In [149]:
# How to creat a multidimentional array

arr = np.array([[1,2,3],
               [4,5,6 ]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
arr.ndim

2

In [159]:
arr.shape

(2, 3)

In [160]:
arr.size

6

In [164]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
# Array reshaping
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [169]:
reshaped2 = arr.reshape(3,2)
reshaped2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [251]:
# ravel --> convert 1 array
ravel = reshaped2.ravel()
ravel

array([100,   2,   3,   4,   5,   6])

In [ ]:
# ravel --> convert 1 array

ravel = reshaped2.ravel()
ravel[0] = 100
print(ravel)
print(reshaped2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
# flatten --> to 1D array
# return the copy of an array

flat = reshaped2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [173]:
flat[0] = 1
flat

array([1, 2, 3, 4, 5, 6])

# Arithematic Operation on Array

In [ ]:
#Addition

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [175]:
# Subtraction
print(a-b)

[-3 -3 -3]


In [176]:
print(b-a)

[3 3 3]


In [177]:
# division
print(a/b)

[0.25 0.4  0.5 ]


In [179]:
# Multiplication
print(a*b)

[ 4 10 18]


In [ ]:
# Floar division
print(b//a)

[4 2 2]


In [181]:
# Modulus --> reminder
print(b%a)

[0 1 0]


In [182]:
# exponent
print(a**2)

[1 4 9]


Universl function Ufunc

In [ ]:
arr = np.array([2,34,5,7])

In [185]:
# Squar root
print(np.sqrt(arr))

[1.41421356 5.83095189 2.23606798 2.64575131]


In [186]:
# exponential -> np.exp -> x is nay integer
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [188]:
# sine function -> np.sine

angle = np.array([0, np.pi, np.pi/2])
print(np.sin(angle))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


# Indexing and Slicing

In [1]:
# Accessing last three element
import numpy as np
arr = np.array([1,2,3,4,5])
arr[-1:-4:-1]

array([5, 4, 3])

In [2]:
arr[:4]

array([1, 2, 3, 4])

In [3]:
arr[: :2]

array([1, 3, 5])

In [4]:
# Negative Indxing

arr[-1]

np.int64(5)

# Multidimentional slicing

In [5]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [7]:
print(matrix[0:2])

[[1 2 3]
 [4 5 6]]


In [8]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [9]:
print(matrix[1: , 2:])

[[6]
 [9]]


In [10]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [11]:
# np.take --> Build in function to perform indexing and slicing

In [12]:
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [13]:
# Iterating with nditer()
arr = np.array([[2,3],
               [4,5]])


In [14]:
for x in np.nditer(arr):
     print(x, end = " ")

2 3 4 5 

In [ ]:
# ndenumerate() -> both index + value

arr = np.array([10,20,30,40,50]) # Accessing 0 2 4
arr[::2]


array([10, 30, 50])

In [17]:
# Negative indexing
print(arr[-1])

50


In [18]:
# Multidimentional slicing

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [19]:
print(matrix[0:2, 0:3])

[[1 2 3]
 [4 5 6]]


In [20]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]
